### ISSUE TITLE
Checklist of the Whole backend

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#268]
Please read the followings and make sure that all that there is, is already implemented in the backend and if there's implemented but not mentioned in the list, or if something needs to be implemented and we haven't think of before, added them and edit the list.

All the:

- [ ] Routes
- [ ] Models
- [ ] Controllers
- [ ] Models' mock data
- [ ] Mock DB file (controllers that manipulate mock data)
- [ ] Auto insertion driver
- [ ] Utils (Querying database with)
- [ ] JWT (Authentication)
- [ ] Validations
- [ ] Swagger
- [ ] Docker

**Comment by MuhammadKhalilzadeh** [comment]
Check what's been done, and for what's not, create its issue right from this page

**Comment by HarshP4585** [comment]
I have checked everything, and it looks fine to me 👍 
NOTE: For now the JWT is disabled, which we need to enable it later.
