### ISSUE TITLE
Small fixes in Compliance Tracker main page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#279]
- [x] Let's remove "ICON" word in the first column.
- [x] Keep the icon column 100px wide so the next column has more space.
- [x] When there is a mouse over, bg color should be #FBFBFB and mouse icon should change to a pointer.
- [x] Change of "SUBCONTROL NAME" column name to "CONTROL NAME"
- [x] Topic area height should be 42px and control area height should be 36px. The reason we are doing this is that when those numbers are applied, all the controls are completely visible on most monitors.

Please see this image for a better explanation of row heights and icon column width.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/143a63e2-eadf-4f3a-a283-269441b32564">

**Comment by melpsh** [comment]
The UI updated as requested:

![image](https://github.com/user-attachments/assets/03ce2f55-778e-4bd1-ae08-6ebd4516fb20)

background color is a bit different and mouse changes to 'Pointer'
