### ISSUE TITLE
Assessment Tracker Calculations

### ISSUE THREAD

**Issue by MuhammadKhalilzadeh** [bluewave-labs/verifywise#397]
- [ ] Pending assessments: All the incomplete assessment questions
- [ ] Approved assessments: This area will be changed to "Implemented assessments", and this number will be calculated from non-zero characters in the editor. 
- [ ] Assessment completion: Percentage of completed assessments divided by number of app assessments.

![Screenshot 2024-12-29 110125](https://github.com/user-attachments/assets/b9aa8938-3b14-437a-8b9c-29b0d6733113)

**Comment by melpsh** [comment]
@MuhammadKhalilzadeh @HarshP4585 Hi guys, I tried to find the calculation function in the assessment tracker controller, but I don't see any. Could you please provide the API?
