### ISSUE TITLE
Assessment tracker view design

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/verifywise#9]
Assessment tracking in AI governance refers to the systematic monitoring and documentation of various evaluations conducted to ensure that an AI system complies with ethical, legal, and regulatory standards. 

These assessments can include risk assessments, bias and fairness checks, accountability audits, security reviews, and regulatory compliance verifications.

VerifyWise Assessment tracker is a page which includes a summary of the assessment for the project chosen (on the top right hand side). 

<img width="1165" alt="Screenshot 2024-09-19 at 11 59 45 AM" src="https://github.com/user-attachments/assets/6681da31-8bd8-47bc-a236-663d396f4477">

When the user clicks on "Go to assessments", the list of assessments on the left hand side, together with what to be filled in on the right hand side is shown. 

![Assessment tracker](https://github.com/user-attachments/assets/f3264341-faf8-4820-8fea-2c0ee3ad1f51)

Tasks: 

- [x] Create the main assessments summary page for the active project.
- [x] Create the assessment details page
   - [x] Show a list of assessments on the left hand side
   - [x] Show a list of details pointing to the assessment on the right hand side

**Comment by gorkem-bwl** [comment]
Hi @MatthewSharpOTU - FYI; there was a project selector on the top right-hand side of the screen. It has been moved to the sidebar, so you don't have to add it to your design since it will be taken care by the sidebar. 

<img width="1050" alt="Screenshot 2024-09-24 at 10 50 53 PM" src="https://github.com/user-attachments/assets/c4c38ff7-daf5-454f-8ccf-b15030bbeb81">

**Comment by gorkem-bwl** [comment]
Documents attached: 

- [More information](https://docs.google.com/document/d/1Am27mVYJ8gfWSzqKCAtSyxvIpm_m-W0icC87svpLFkU/edit?tab=t.0) on the assessment tracker page implementation
- [A template](https://docs.google.com/spreadsheets/d/19SX-3ksQwaz1nekvWkNFE-7-oDv2zJF2IpBjKyW4ozc/edit?gid=0#gid=0) for the assessment tracker page

**Comment by gorkem-bwl** [comment]
@MuhammadKhalilzadeh Just a heads up that the previous template was removed above and 'All questions' section has been added. This is the same file shared with you earlier today.
